<?php

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function dmt_group_comments_comment_insert(Drupal\Core\Entity\EntityInterface $entity) {
  if($entity->bundle() == 'group_comments') {
    $activity_action_manager = \Drupal::service('plugin.manager.activity_action_processor');
    $create_action = $activity_action_manager->createInstance('create_activity_action');
    $create_action->create($entity);
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function dmt_group_comments_entity_view_alter(array &$build, ContentEntityInterface $entity, EntityViewDisplayInterface $display) {
  $commands_added = &drupal_static(__FUNCTION__);
  if (!isset($commands_added)) {
    $commands_added = FALSE;
  }

  if (!$commands_added) {
    foreach ($entity->getFieldDefinitions() as $machine_name => $field_config) {
      if ($field_config->getType() === 'comment') {
        /** @var \Drupal\ajax_comments\FieldSettingsHelper $field_settings_helper */
        $field_settings_helper = \Drupal::service('ajax_comments.field_settings_helper');
        $field_formatter = $field_settings_helper->getFieldFormatter($display, $machine_name, $field_config, $display->getMode());
        if (!empty($field_formatter) && $field_settings_helper->isEnabled($field_formatter)) {
          $build['#attached']['library'][] = 'dmt_group_comments/comment-box';
          $commands_added = TRUE;
          break;

        }
      }
    }
  }
}
