<?php

/**
 * @file
 * Contains activity_basics.module..
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function activity_basics_entity_insert(EntityInterface $entity) {
  /* @var \Drupal\activity_creator\Plugin\ActivityActionManager $activity_logger_factory */
  $activity_logger_factory = \Drupal::service('plugin.manager.activity_action.processor');
  // Trigger the create action for entities.
  /* @var \Drupal\activity_creator\Plugin\ActivityActionInterface $create_action */
  $create_action = $activity_logger_factory->createInstance('create_entity_action');
  $create_action->create($entity);
}
