<?php

/**
 * @file
 * Contains activity_basics.module..
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function activity_basics_entity_insert(EntityInterface $entity) {
  // get current node bundle
  $bundle = $entity->bundle();
  // check if current node is organisation node
  if ($entity instanceof Node && 'issue' === $bundle ) {
    /* @var \Drupal\activity_creator\Plugin\ActivityActionManager $activity_logger_factory */
    $activity_logger_factory = \Drupal::service('plugin.manager.activity_action.processor');
    // Trigger the create action for entities.
    /* @var \Drupal\activity_creator\Plugin\ActivityActionInterface $create_action */
    $create_action = $activity_logger_factory->createInstance('create_activity_action');
    $create_action->create($entity);
  }
}



