<?php

/**
 * @file
 * Contains activity_basics.module..
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\group\Entity\GroupContent;

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function activity_basics_entity_insert(EntityInterface $entity) {

  $nid = NULL;

  switch($entity->getEntityTypeId()) {
    case 'node':
      $activity_entity = $entity;
      break;
    case 'group_content':
      $activity_entity = Node::load( $entity->get('entity_id')->getValue()[0]['target_id'] );
      break;
  }

  if($activity_entity) {
    /* @var \Drupal\activity_creator\Plugin\ActivityActionManager $activity_logger_factory */
    $activity_logger_factory = \Drupal::service('plugin.manager.activity_action.processor');
    // Trigger the create action for entities.
    /* @var \Drupal\activity_creator\Plugin\ActivityActionInterface $create_action */
    $create_action = $activity_logger_factory->createInstance('create_activity_action');
    $create_action->create($activity_entity);
  }



}



