<?php

/**
 * @file
 * Contains activity_creator.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function activity_creator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the activity_creator module.
    case 'help.page.activity_creator':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function activity_creator_theme() {
  $theme = [];
  $theme['activity'] = array(
    'render element' => 'elements',
    'file' => 'activity.page.inc',
    'template' => 'activity',
  );
  $theme['activity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'activity.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function activity_creator_theme_suggestions_activity(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#activity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'activity__' . $sanitized_view_mode;
  $suggestions[] = 'activity__' . $entity->bundle();
  $suggestions[] = 'activity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'activity__' . $entity->id();
  $suggestions[] = 'activity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
