<?php
/**
 * Created by PhpStorm.
 * User: X
 * Date: 25.1.2017.
 * Time: 17:01
 */


use Drupal\user\Entity\User;
use Drupal\personas\Entity\Persona;

/**
 * Create Test User Accounts for every Role
 */

function dmt_dev_create_test_accounts() {
  $personas = Persona::loadMultiple();
  foreach ($personas as $persona) {
    /** @var Persona $persona */
    $mail = $persona->id() . "@dv.com";
    $user_exists = user_load_by_mail($mail);
    if (empty($user_exists)) {
      $user = User::create(array(
        'name' => 'TEST_'.$persona->id(),
        'mail' => $mail,
        'status' => 1,
        'pass' => $persona->id(),
        'roles' => array($persona->id())
      ));
      $user->save();
    }
  }
}

/**
 * Mail Reroute
 * Implements hook_mail_alter().
 * Override ALL 'to' parametars in email sending so you can test survey sending with your email
 */

function dmt_dev_mail_alter(&$message) {
  $message['to'] = 'adriadrop@gmail.com';
}

/**
 * Set Default features bundle that we work with
 * TODO check user is admin
 * @param $account
 */
function dmt_dev_user_login($account) {
  $session = \Drupal::request()->getSession();
  if (isset($session)) {
    $session->set('features_current_bundle', 'dv');
  }
}