<?php

/**
 * @file
 * Contains dv_positions.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dv_positions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dv_positions module.
    case 'help.page.dv_positions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DV Positions') . '</p>';
      return $output;

    default:
  }
}
