<?php

/**
 * Implements hook_moderation_state_machine_parent_entity_alter().
 */
function dmt_mailing_list_moderation_state_machine_parent_entity_alter(&$parent_entity, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\workflows\Entity\Workflow $workflow) {
  if($entity->getEntityTypeId() == 'activity' && $entity->bundle() == 'mailing_list_activity') {
    /** @var \Drupal\activity_creator\Entity\Activity $entity */
    $parent_entity = $entity->get('field_activity_mailing_list')->entity;
  }
}
