# Note that the example .travis.yml file for child projects lives in /install.
# Temporarily use legacy infrastructure until Travis resolves MySQL issues with their containerized infrastructure.
# @see https://github.com/travis-ci/travis-ci/issues/6842
sudo: required
language: php
dist: trusty

php:
  - 5.6

matrix:
  fast_finish: true

env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
    - BUILD_DIR=$TRAVIS_BUILD_DIR

jdk:
  - oraclejdk8

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - "vendor"
  # Cache front end dependecies to dramatically improve build time.
  - "docroot/themes/custom/patternlab/node_modules"
  - "docroot/themes/custom/patternlab/bower_components"

addons:
  ssh_known_hosts:
  # - svn-4786.devcloud.hosting.acquia.com
  - svn-5223.devcloud.hosting.acquia.com
  - svn-6182.devcloud.hosting.acquia.com

  # code climate integration
  code_climate:
    secure: hhFEmNdJQU4ui8ph2cdATzjU3QVxLdrugJSTcgoKJ0QVi7sV1Bk0LHa47icb6iCGg7mbljYoyeeVRZlCjVzx35vC+s34049WJDo/WMlZuscB3a6Z4UwDXC0oJl4j2VzCgdXPo9S40aDrtiLyM6Gj4ETy/kf4idL5PYVvEQiERsN7H9bchjoLtmNIbTYYyNVFqRoRwSvc0g2RT+Fu43hFeTQiHpNJ9bUZyautQKJ/gga2wirCiIqBrZPbocRkdJSxwJEzfQwKTu4AYjMtoRMW7W+mZsiXmxdteM8CpEM5PbXREC2AzXS9F8/+IGDk5riqVGobvvFtnp26MJBBS8UuVRHvN05D7Hf3FH5URg7EwRw/EWSSiGp/gmknRN2WGBiO/AQzekJ2oXHLTWbYxOYxfzjWFFD9gPbLNb3IdZhwYQnHjqkKjeYv88umo0mE1AUI4VAQKmQKfMQW/t3TN2fP2JWu4sghG1G1AJP015jAJ0h0S+esG+2k9UJMGgtdvE/xyjVaXm8tj+w71PiICo+1NNIg/R6NsD5imhJ0KZRydg5zAm2hLZQl5etmuaXajl9otgBqbX5xs2ueNcudecXn2CIfxCOyky175aDHcFZCYa8TkQxD7i8BQrERma1BFVUGv7Z+NDhFagtVcjCssn7jk9/7C2CCjQ0y6zBjer5MZtE=
  # saucelabs integration
#  sauce_connect:
#    username: ttoman
#  jwt:
#    secure: IEI6dd8+Xj3yxfJWvPLwyXra7eqkxR7UoHp5ofMxG+djWCKnwHR6H12rgkTZ5nbrv1DeX+DBOMI/ZraLWO89EzW+LLEiJbqpJNF5dulUE+MIpC11JiEiE+87g0VQfqu4l33tFHdrTwpBuHSCCVcAWMv7byPlaM34q2d8UhpP8SgJxhdzrK9UlpN66zi5tti+i59b4iRnnn1V1ATS2GIW2LRWt9OoJDgGOpQKtrnl3jdcw51v6rMnCvFEI7lLxKR2JJ0xC7IRxwvSvM+9Ku8njw0G0owKz4obNKf62sMGsV1d93SMcHDNaok5lf3eOBKg2Q21JPUw7vab+Kej32ZyCtqQKAVWoZaL/4LVsaeHPdZDbjFudTi98GdA8yIlyOfsqIVXNgYGsPL+FObRFxPezMM3laVQuvZCTI+x+rhctxwBlRF8CwbyaDzJ/wTgk6HW0eQwhCQzEpriNeJyez7VrXOeA6rfUdaxbs3f/NiZEszAL6UBkteJ0VVDbGmoyyPtm4vw2aM6ujLrIe/BAkku1wstzVYy1aTUEY6IxdgMkxEOyU42z2UmBOUIEeIg4cCE6qIgckpLtrW0YCYUmhX9eDeLl9dIO8W617hhil3G9nNvLmnaDl/puUprM6mIUN8HGzrHmBbTqYxY/sAizgKXYQI+P5z401ZQ++a2WTilpFI=
# @see https://docs.travis-ci.com/user/notifications
notifications:
# - hipchat: [api token]@[room id or name]
# - slack: '<account>:<token>#[channel]'
  slack:
    secure: dzFsX8by42nys1YDMsX7XpANi/F42Wonj9oSf5frexWY4CX/SryQNZRtysRbLeEqymVSEWdFfyfG6O+Nu7CjuyKoQvuxI5oU+8N7qmvpkT8BFG7pjb+trOS7ykJZQ9d/U7ltSoPfgK9nZOD7h33jk1Ub0YL1fSngUqJe1GjFTk4atsEB56XGO/dHj634OJ7TVXPwwjDUAsKC/ZAeoH6VtfZUWyY/XJDH008Xq1GEx54QlcNKiPhbWYNCbYPrphnKs4RX6ypkzKqIXdeZPm2qkyOO/pu6pRJrb9cfX739BgKmyksmTH3jhddGjuwFQHQ1Ur9/VGtGVCBHPl3BenMNf65/Vjt26d0NoD1duQ7z2XUfcwp50CCC24WTR9nHuC06+1AxyyUNBpcvhx+WeJ4z7TwLIl3ZBKcLtTRGq43gNHP8RUTH2RxFZlcbN13NomT7gjC63ugyOAoTgECV+CCLMOblH11Gx+Ufqj5pHn1vqh4gO2IAKF4rFmP7tQ+iKFPZT/jPwj4ZHr2036yy75k5YqyU+2CYSdxIULE9kNhfmoz7omzPlW4+AprWTjMgN0v9A9skXSr9FZ01wX8mBxSxpM1g7Q8RfPkU8MmNzn2Fb1bp1BvAvqiIwsaWAplka/8MHuY1L8vqJtKIIeybw11wwpFgx7b9IbFwRnO+VK77Fjw=

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  - echo 'sendmail_path = "/bin/true"' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"
  - echo "memory_limit=520M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer validate --no-check-all --ansi
  - composer install
  - composer global require daux/daux.io

install:
  - nvm install 6.2.2
  - nvm use 6.2.2
  - source ${BLT_DIR}/scripts/travis/setup_environment
  - source ${BLT_DIR}/scripts/travis/setup_project

before_script:
  - phpenv config-add travis.php.ini
  - npm install -g gulp-cli

script:
#  - source $BLT_DIR/scripts/travis/run_tests
# Copied from above file because we needed to add travis_wait
#  - set -ev
#  - yaml-cli update:value blt/project.yml project.local.hostname '127.0.0.1:8888'
#  - travis_wait 30 blt ci:build:validate:test -Dcreate_alias=false -Dbehat.run-server=true -Dblt.verbose=true
#  - set +v
  - source ${BLT_DIR}/scripts/travis/run_tests

# Support for CodeClimate
#after_script:
#  - ./vendor/bin/test-reporter


before_deploy:
# Decrypt private key
  - openssl aes-256-cbc -K $encrypted_3fec15fb840c_key -iv $encrypted_3fec15fb840c_iv -in travis_acquia_pri.ppk.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - ls -lash ~/.ssh
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - cd ${BUILD_DIR}/docroot/profiles/dv/docs
  - ~/.composer/vendor/daux/daux.io/bin/daux --destination=${BUILD_DIR}/docs --configuration=global.json

deploy:
   - provider: script
     script: "$BLT_DIR/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: master
       php: 5.6
   - provider: pages
     local-dir: docs
     skip-cleanup: true
     github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
     keep-history: true
     on:
       branch: develop
