<?php

/**
 * @file
 * Install, update and uninstall functions for the geo_area_migrate module.
 */

/**
 * Implements hook_uninstall().
 */
function geo_area_migrate_uninstall() {
  $config_names = [
    'migrate_plus.migration.geoarea',
    'migrate_plus.migration_group.geoarea'
  ];

  // Delete each config using configFactory.
  foreach ($config_names as $config_name) {
    \Drupal::configFactory()->getEditable($config_name->name)->delete();
  }
}