<?php

/**
 * @file
 * Contains wireframe_overlay.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wireframe_overlay_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wireframe_overlay module.
    case 'help.page.wireframe_overlay':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Wireframe Overlay.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function wireframe_overlay_theme($existing, $type, $theme, $path) {
  return [
    'wireframe_overlay' => [
      'variables' => ['toggle' => NULL, 'label' => NULL, 'description' => NULL, 'image' => NULL],
    ],
  ];
}

Function wireframe_overlay_preprocess_html(&$variables) {

  $wireframe_overlay = Drupal::service('wireframe_overlay.data')->overlayData();
  //Add a JS library
  if($wireframe_overlay) {
    $variables['#attached']['library'][] = 'wireframe_overlay/wireframe-overlay';
    $variables['#attached']['library'][] = 'core/jquery.ui.slider';
    $variables['#attached']['drupalSettings']['wireframe_overlay'] = $wireframe_overlay;
  }
}
