<?php

/**
 * @file
 * Contains dmt_organisation.module.
 */

use Drupal\profile\Entity\Profile;
use Drupal\group\Entity\Group;

/**
 * Implements hook_entity_presave().
 *
 * @param \Drupal\profile\Entity\Profile $profile
 */
function dmt_organisation_profile_presave(Profile $profile) {
  $bundle = $profile->bundle();

  if ($bundle == 'organisation_profile') {
    $organisation_id = $profile->get('field_org_organisation_id')->getValue();
    if (empty($organisation_id)) {
      $user = $profile->getOwner();
      $organisation_id = Drupal::service('dmt_organisation.organisation')
        ->getOrganisationIdByUser($user);

      $profile->set('field_org_organisation_id', $organisation_id);
    }
  }
}


/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function dmt_organisation_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle) {
  if ($bundle === 'organisation_profile') {
    if (isset($fields['field_org_organisation_id'])) {
      $fields['field_org_organisation_id']->addConstraint('UniqueOrganisationID', []);
    }
  }
}


/**
 * Implements hook_profile_insert().
 *
 * @param \Drupal\profile\Entity\Profile $profile
 */
function dmt_organisation_profile_insert(Profile $profile) {
  $bundle = $profile->bundle();

  if ($bundle == 'organisation_profile') {
    \Drupal::service('dmt_organisation_group.add_group_to_subgroup')
      ->add($profile, 'organisation', 'field_org_parent_organisation');
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function dmt_organisation_profile_update(Profile $profile) {

//  Keep Organisation
  $bundle = $profile->bundle();

  if ($bundle == 'organisation_profile') {

    $org_title = $profile->field_org_title->value;
    $org_group_id = Drupal::service('dmt_organisation.organisation')
      ->getRelatedOrganisationGroupId($profile);
    $group = Group::load($org_group_id);

    if ($org_title != $group->label()) {
      $group->set('label', $org_title);
      $group->save();
    }
  }
}
