<?php

/**
 * @file
 * Contains dmt_organisation.module.
 */

use Drupal\profile\Entity\Profile;

/**
 * Implements hook_entity_presave().
 *
 * @param \Drupal\profile\Entity\Profile $profile
 */
function dmt_organisation_profile_presave(Profile $profile) {
  $bundle = $profile->bundle();

  if ($bundle == 'organisation_profile') {
    $organisation_id = $profile->get('field_org_organisation_id')->getValue();
    if (empty($organisation_id)) {
      $organisation_id = Drupal::service('dmt_organisation.organisation')
        ->getOrganisationId();

      $profile->set('field_org_organisation_id', $organisation_id);
    }
  }
}


/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function dmt_organisation_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle) {
  if ($bundle === 'organisation_profile') {
    if (isset($fields['field_org_organisation_id'])) {
      $fields['field_org_organisation_id']->addConstraint('UniqueOrganisationID', []);
    }
  }
}