<?php

/**
 * @file
 * Contains organisation_group.module..
 */

/**
 * Implements hook_entity_insert().
 */
function dv_user_groups_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node') {
    // check bundle
    if ('issue' === $entity->bundle()) {
      \Drupal::service('dv_user_groups.user_group')->groupUserIssue($entity, 'insert');
    }
  }
}

/**
 * Implements hook_entity_update().
 */
function dv_user_groups_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node') {
    // check bundle
    if ('issue' === $entity->bundle()) {
      \Drupal::service('dv_user_groups.user_group')->groupUserIssue($entity, 'update');
    }
  }
}
