<?php

/**
 * @file
 * Contains geo_area_group.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function geo_area_group_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the geo_area_group module.
    case 'help.page.geo_area_group':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Geo Area Group') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_entity_insert().
 */
function geo_area_group_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node') {

    // get current node bundle
    $bundle = $entity->bundle();

    // check if current node is geo_area node
    if ('geo_area' === $bundle) {
      \Drupal::service('dmt_group.add_group_to_subgroup')->add($entity, 'geo_area_group', 'field_geo_area_parent');
    }

  }
}
