<?php

/**
 * @file
 * Contains dmt_group.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function dmt_group_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dmt_group module.
    case 'help.page.dmt_group':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DMT Group.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * @param Node $entity
 */
function dmt_group_node_update(Node $entity) {

  \Drupal::service('dmt_group.node_queue_helper')->queueNode($entity);

}

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * @param Node $entity
 */
function dmt_group_node_insert(Node $entity) {

  \Drupal::service('dmt_group.node_queue_helper')->queueNode($entity);

}
