<?php

/**
 * @file
 * Contains dmt_group.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\group\Entity\Group;

/**
 * Implements hook_help().
 */
function dmt_group_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dmt_group module.
    case 'help.page.dmt_group':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DMT Group.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function dmt_group_entity_update(EntityInterface $entity) {

  if ($entity instanceof Node) {

    // get current node bundle
    $bundle = $entity->bundle();
    $moderation_state = $entity->get('moderation_state')->getString();

    // check if current node is organisation node
    if ($moderation_state === 'send_email') {

      // check if current node is organisation node
      if ('issue' === $bundle || 'survey' === $bundle) {
        $data['entity_id'] = $entity->id();
        $queue = \Drupal::queue('dv_organisation_extract_one');

        foreach ($entity->get('field_recipient')
                   ->getValue() as $recipient_group) {
          $data['gid'] = $recipient_group['target_id'];
          $queue->createItem($data);
        }

      }
    }
  }
}

function test_group() {
  $gid = 3;

  $group = Group::load($gid);

  $test = $group->getContent('group_node:organisation');

  dpm($test);

}
