<?php

/**
 * @file
 * Contains organisation_group.module..
 */

/**
 * Implements hook_entity_insert().
 */
function dmt_user_groups_node_insert(Drupal\Core\Entity\EntityInterface $entity) {
  if ('issue' === $entity->bundle()) {
    \Drupal::service('dmt_user_groups.user_group')
      ->groupUserIssue($entity, 'insert');
  }
}

/**
 * Implements hook_entity_update().
 */
function dmt_user_groups_node_update(Drupal\Core\Entity\EntityInterface $entity) {
  if ('issue' === $entity->bundle()) {
    \Drupal::service('dmt_user_groups.user_group')
      ->groupUserIssue($entity, 'update');
  }
}
