<?php

/**
 * @file
 * Contains dmt_mail.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

// @todo #11 this whole file is currently unneeded so it should be removed

/**
 * Implements hook_help().
 */
function dmt_mail_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dmt_mail module.
    case 'help.page.dmt_mail':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DMT mail.') . '</p>';
      return $output;

    default:
  }
}
