---
- hosts: localhost
  become: yes

  vars_files:
    - ../../vendor/geerlingguy/drupal-vm/provisioning/vars/main.yml
    - ../../vendor/geerlingguy/drupal-vm/default.config.yml
    - config.yml

  pre_tasks:
    - name: get the username running the deploy
      local_action: >
        command whoami
      register: local_username
      become: no

    - name: Set php_fpm_pool_user variable
      set_fact:
        php_fpm_pool_user: '{{ local_username.stdout }}'

    - name: Set php_fpm_pool_group variable
      set_fact:
        php_fpm_pool_group: '{{ local_username.stdout }}'

    - debug:
        var: php_fpm_pool_group