<?php

/**
 * @file
 * Contains organisation_group.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dv_organisation_group_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the organisation_group module.
    case 'help.page.organisation_group':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Organisation Group.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_insert().
 */
function dv_organisation_group_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node') {

    // get current node bundle
    $bundle = $entity->bundle();

    // check if current node is organisation node
    if ('organisation' === $bundle) {
      \Drupal::service('dmt_group.add_group_to_subgroup')->addOrganisation->add($entity, 'organisation', 'field_o_parent_organisation');
    }

  }
}
