<?php

/**
 * @file
 * Contains dvm_user.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function dvm_user_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dvm_user module.
    case 'help.page.dvm_user':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}