- hosts: localhost

  vars_files:
    - vars/php.yml

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
      become: true
    - role: geerlingguy.composer
      become: true
    - role: gantsign.maven
      inotify_max_user_watches: 524288
    - role: wtanaka.slack