- hosts: localhost
  become: yes

  vars_files:
    - vars/php.yml

  vars:
    - git_install_from_source: true
    - git_install_from_source_force_update: true
    - git_version: "2.14.1" # has to be > 2.10 because of composer patching

  pre_tasks:
    - name: get the username running the deploy
      local_action: >
        command whoami
      register: local_username
      become: no

    - name: Install C libraries for compilation packages from source (Debian).
      apt: "name={{ item }} state=installed"
      with_items: ["libcurl4-openssl-dev", "libexpat1-dev", "libz-dev", "libssl-dev"]
      update_cache: yes

    - name: Set git file.Mode false
      shell: git config core.fileMode false
      become: no

    - name: Git Push default matching
      shell: git config --global push.default matching
      become: no

    - name: Cache Github credentials
      shell: git config credential.helper 'cache --timeout=3000000000000000000000'
      become: no

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ local_username.stdout }}"
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: geerlingguy.composer
    - role: gantsign.inotify
      inotify_max_user_watches: 524288
    - role: maanas.curl
    - role: wtanaka.slack
    - role: bearandgiraffe.yarn
    - role: martinmicunda.nodejs
    - role: martinmicunda.gulp
    - role: geerlingguy.git
    - role: andrewrothstein.hub

  tasks:
    - name: Install project using Composer
      shell: chdir=/var/www/dv composer install --no-interaction
      become: no

    - name: Purge PHP used for Composer
      shell: apt-get remove -y --purge "php*"

    - name: Remove PHP config
      shell: rm /etc/php -R