- hosts: localhost
  become: true

  vars_files:
    - vars/php.yml

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: geerlingguy.composer
    - role: gantsign.inotify
      inotify_max_user_watches: 524288
    - role: wtanaka.slack
