- hosts: localhost
  become: yes

  vars_files:
    - vars/php.yml

  pre_tasks:
    - name: get the username running the deploy
      local_action: >
        command whoami
      register: local_username
      become: no

    - name: Set git file.Mode false
      shell: git config core.fileMode false
      become: no

    - name: Git Push default matching
      shell: git config --global push.default matching
      become: no

    - name: Cache Github credentials
      shell: git config credential.helper 'cache --timeout=3000000000000000000000'
      become: no

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ local_username.stdout }}"
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: geerlingguy.composer
    - role: gantsign.inotify
      inotify_max_user_watches: 524288
    - role: maanas.curl
    - role: wtanaka.slack
    - role: bearandgiraffe.yarn
    - role: AsianChris.gulp

  tasks:
    - name: Install project using Composer
      shell: chdir=/opt/tools/temp composer install --no-interaction
      become: no

    - name: Purge PHP used for Composer
      shell: apt-get remove -y --purge "php*"

    - name: Remove PHP config
      shell: rm /etc/php -R

    - name: Run server install playbook
      shell: chdir=/var/www/dv/install/lamp ansible-playbook playbook.yml

    - name: Create project.local.yml
      shell: touch /var/www/dv/blt/project.local.yml
      become: no

    - name: Add config to project.local.yml
      shell: "echo 'environment: local' >> test.txt"
      become: no

    - name: Make default directory writable
      shell: chmod -R +w /var/www/dv/docroot/sites/default

    - name: Run site installation with BLT
      shell: chdir=/var/www/dv vendor/bin/blt custom:reinstall
      become: no