- hosts: localhost

  vars_files:
    - vars/php.yml

  pre_tasks:
    - name: Set git file.Mode false
      shell: git config core.fileMode false
    - name: Git Push default matching
      shell: git config --global push.default matching
    - name: Cache Github credentials
      shell: git config credential.helper 'cache --timeout=3000000000000000000000'

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"
    - role: geerlingguy.php-versions
      become: true
    - role: geerlingguy.php
      become: true
    - role: geerlingguy.composer
      become: true
    - role: gantsign.inotify
      inotify_max_user_watches: 524288
      become: true
    - role: maanas.curl
      become: true
    - role: wtanaka.slack
      become: true
    - role: manala.yarn
      become: true
    - role: AsianChris.gulp
      become: true
