# Install a roles from the Ansible Galaxy
- src: gantsign.oh-my-zsh
- src: geerlingguy.php-versions
- src: geerlingguy.php
- src: geerlingguy.composer
- src: gantsign.inotify
- src: maanas.curl
- src: wtanaka.slack
- src: bearandgiraffe.yarn
- src: martinmicunda.nodejs
- src: martinmicunda.gulp
- src: geerlingguy.git