# Install a roles from the Ansible Galaxy
- src: gantsign.oh-my-zsh
- src: geerlingguy.php-versions
- src: geerlingguy.php
- src: geerlingguy.composer
- src: gantsign.inotify
- src: wtanaka.slack
- src: manala.yarn