<?php

/**
 * @file
 * Contains dvm_mailing_list.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\group\Entity\Group;
use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_help().
 */
function dvm_mailing_list_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dvm_mailing_list module.
    case 'help.page.dvm_mailing_list':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DV Mailing list') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function dvm_mailing_list_form_group_mailing_list_add_form_alter(&$form, $form_state, $form_id) {
  // Add custom submit handler
  // $form['actions']['submit']['#submit'][] = '_dvm_mailing_list_group_form_submit';

}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dvm_mailing_list_form_group_mailing_list_edit_form_alter(&$form, $form_state, $form_id) {
  // Add custom submit handler
  // $form['actions']['submit']['#submit'][] = '_dvm_mailing_list_group_form_submit';
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function dvm_mailing_list_form_node_question_form_alter(&$form, FormStateInterface &$form_state) {
  $form['title']['#access'] = FALSE;

  $form['revision_information']['#access'] = FALSE;

  $form['body']['widget']['#title'] = '';

  $form['body']['widget'][0]['#title_display'] = 'hidden';

  $ajax_id = 'ajax-form-entity-node-question-new';

  $form['#attributes']['class'][] = $ajax_id;

  // Ajaxification settings of the buttons.
  $ajax_settings = array(
    'callback' => 'Drupal\dvm_mailing_list\Form\QuestionFormAlter::ajaxFormEntityCallback',
    'wrapper' => $ajax_id,
    'effect' => 'fade',
  );
  $form['actions']['submit']['#ajax'] = $ajax_settings;
  $form['actions']['publish']['#ajax'] = $ajax_settings;
  $form['actions']['unpublish']['#ajax'] = $ajax_settings;
  // @todo : does not work with dropbuttons (needs javascript magic presumably).
  unset($form['actions']['publish']['#dropbutton']);
  unset($form['actions']['unpublish']['#dropbutton']);
  // Ajaxify the buttons.
  foreach (array_keys($form['actions']) as $action) {
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'Drupal\dvm_mailing_list\Form\QuestionFormAlter::ajaxFormEntityNodeFormSubmit';
    }
  }

}

/**
 * Auto generate title for question node.
 *
 * Implements hook_entity_presave().
 */
function dvm_mailing_list_node_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if($entity->bundle() == 'question') {
    /** @var  \Drupal\node\Entity\Node $entity */
    $body_value = strip_tags($entity->get('body')->getValue()[0]['value']);
    $title = substr($body_value, 0 , 254);
    $entity->set('title', $title);
    $entity->isDefaultRevision(TRUE);
  }
}

/**
 * Trigger batch on approved state.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function _dvm_mailing_list_group_form_submit($form, \Drupal\Core\Form\FormStateInterface $form_state) {

  $group = $form_state->getFormObject()->getEntity();
  $mod_state = $group->get('moderation_state')->getValue()[0]['value'];

  if($mod_state === 'published') {

    /** @var \Drupal\Core\Url $redirect */
    $redirect = $form_state->getRedirect();
    $group_id = $redirect->getRouteParameters()['group'];

    // getMembership gids
    $gids = $form_state->getValue('field_ml_to');

//  getIssue nids
    $group = Group::load($group_id);
    $nids = $group->get('field_ml_questions')->getValue();

    $batch = array(
      'title' => t('Set up Survey...'),
      'operations' => array(
        array(
          '\Drupal\dvm_mailing_list\BatchMailingList::cleanGroup',
          array($group_id)
        ),
        array(
          '\Drupal\dvm_mailing_list\BatchMailingList::addMembers',
          array($gids, $group_id)
        ),
        array(
          '\Drupal\dvm_mailing_list\BatchMailingList::addQuestions',
          array($nids, $group_id)
        ),
      ),
      'init_message' => t('Example Batch is starting.'),
      'progress_message' => t('Processed @current out of @total.'),
      'error_message' => t('Example Batch has encountered an error.'),
      'finished' => '\Drupal\dvm_mailing_list\BatchMailingList::deleteNodeExampleFinishedCallback',
    );
    batch_set($batch);
  }

}
