<?php

/**
 * @file
 * Contains dvm_mailing_list.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\dmt_group\GroupHelper;
use Drupal\node\Entity\Node;


/**
 * Implements hook_help().
 */
function dvm_mailing_list_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dvm_mailing_list module.
    case 'help.page.dvm_mailing_list':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DV Mailing list') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function dvm_mailing_list_form_group_mailing_list_add_form_alter(&$form, $form_state, $form_id) {
  // Add custom submit handler
  $form['actions']['submit']['#submit'][] = '_dvm_mailing_list_group_form_submit';

}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dvm_mailing_list_form_group_mailing_list_edit_form_alter(&$form, $form_state, $form_id) {
  // Add custom submit handler
  $form['actions']['submit']['#submit'][] = '_dvm_mailing_list_group_form_submit';

}


function _dvm_mailing_list_group_form_submit($form, \Drupal\Core\Form\FormStateInterface $form_state) {

  /** @var \Drupal\Core\Url $redirect */
  $redirect = $form_state->getRedirect();
  $group_id = $redirect->getRouteParameters()['group'];


  // getMembership gids
  $gids = $form_state->get('field_ml_to')->getValues();

  // cleanupIssues nids
  $group = Group::load($group_id);


  $batch = array(
    'title' => t('Set up Survey...'),
    'operations' => array(
      array(
        '\Drupal\dvm_mailing_list\BatchMailingList::cleanupMembers',
        array($uids)
      ),
      array(
        '\Drupal\dvm_mailing_list\BatchMailingList::cleanupIssues',
        array($uids)
      ),
      array(
        '\Drupal\dvm_mailing_list\BatchMailingList::getMembership',
        array($gids)
      ),
      array(
        '\Drupal\dvm_mailing_list\BatchMailingList::addMembers',
        array($uids)
      ),
      array(
        '\Drupal\dvm_mailing_list\BatchMailingList::addIssues',
        array($nids)
      ),
    ),
    'init_message' => t('Example Batch is starting.'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('Example Batch has encountered an error.'),
    'finished' => '\Drupal\dvm_mailing_list\BatchAddToGroup::deleteNodeExampleFinishedCallback',
  );
  batch_set($batch);

}
