<?php

/**
 * @file
 * Contains dvm_organisation.module.
 */

use Drupal\profile\Entity\Profile;

/**
 * Implements hook_node_insert().
 *
 * @param \Drupal\profile\Entity\Profile $profile
 */
function dvm_organisation_profile_insert(Profile $profile) {
  $bundle = $profile->bundle();

  if ($bundle == 'organisation_profile') {
    \Drupal::service('dvm_organisation_group.add_group_to_subgroup')
      ->add($profile, 'organisation', 'field_org_parent_organisation');
  }
}

/**
 * Implements hook_entity_presave().
 *
 * @param \Drupal\profile\Entity\Profile $profile
 */
function dvm_organisation_profile_presave(Profile $profile) {
  $bundle = $profile->bundle();

  if ($bundle == 'organisation_profile') {
    $organisation_id = $profile->get('field_org_organisation_id')->getValue();
    if (empty($organisation_id)) {
      $organisation_id = Drupal::service('dvm_organisation.organisation')
        ->getOrganisationId();

      $profile->set('field_org_organisation_id', $organisation_id);
    }
  }

}
