<?php

/**
 * @file
 * Contains organisation_group.module..
 */

use Drupal\group\Entity\Group;
use Drupal\user\Entity\User;

/**
 * Implements hook_entity_insert().
 */
function dvm_organisation_group_node_insert(Drupal\Core\Entity\EntityInterface $entity) {

}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function dvm_organisation_group_group_content_insert(\Drupal\group\Entity\GroupContent $entity) {
  /** @var \Drupal\group\Entity\GroupContentType $group_content_type */
  $group_content_type = $entity->getGroupContentType();

  $plugin_id = $group_content_type->getContentPluginId();

  if ($plugin_id === 'group_node:organisation') {
    /** @var Group $group */
    $group = $entity->getGroup();
    /** @var \Drupal\node\Entity\Node $node */
    $node = $entity->getEntity();

    $query = Drupal::entityQuery('user')
      ->condition('field_ac_organisation_node', $node->id());

    $entity_ids = $query->execute();

    $new_owner = User::load(reset($entity_ids));

    $node->setOwner($new_owner);
    $node->save();

    $group->addMember($new_owner, ['group_roles' => [$group->bundle().'-organisation']]);
  }
}

